GET http://localhost:3001/api/persons
###


GET http://localhost:3001/info
###


GET http://localhost:3001/api/persons/64f4397ddedf58baa672a6f5
###


DELETE http://localhost:3001/api/persons/64f4397ddedf58baa67
###


POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Prabin Bastakoti",
    "number": "9749459505"
}

### 
PUT http://localhost:3001/api/persons/64f43a76dedf58baa6
content-Type: application/json

{
    "name": "Prabin Bastakoti",
    "number": "123456789"
}